
CREATE TABLE IASSIST.COLORES 
(
  IDCOLOR NUMBER NOT NULL 
, NOMBRE VARCHAR2(255) 
, CONSTRAINT COLORES_PK PRIMARY KEY 
  (
    IDCOLOR 
  )
  ENABLE 
);


ALTER TABLE IASSIST.TICKETS ADD IDCOLOR NUMBER;

ALTER TABLE IASSIST.TICKETS ADD 
CONSTRAINT "TICKETS_COLORES_FK" FOREIGN KEY ("IDCOLOR")
	  REFERENCES "IASSIST"."COLORES" ("IDCOLOR") ENABLE;


	        
ALTER TABLE IASSIST.TICKETS
ADD (IDPROBLEMA NUMBER);

ALTER TABLE IASSIST.TICKETS ADD CONSTRAINT "TICKET_PROBLEMA_FK" FOREIGN KEY ("IDPROBLEMA")
	  REFERENCES "IASSIST"."PROBLEMAS" ("IDPROBLEMA") ENABLE;
      
UPDATE IASSIST.TICKETS A
SET A.IDPROBLEMA = (SELECT Z.IDPROBLEMA FROM IASSIST.TICKET_PRESTADORES Z WHERE Z.IDTICKETPRESTADOR = (SELECT MIN(IDTICKETPRESTADOR) FROM IASSIST.TICKET_PRESTADORES WHERE IDTICKET = Z.IDTICKET) AND Z.IDTICKET = A.IDTICKET);

COMMIT;
