
-- Indice de Prestaciones por Ticket
CREATE INDEX TICKET_PREST_BY_TICKET ON TICKET_PRESTADORES (IDTICKET);

-- Indice de Obervaciones por Ticket
CREATE INDEX OBSERVACIONES_BY_TICKET ON OBSERVACIONES (IDTICKET);

-- Creación de Tabla para Tracking de los Tickets
CREATE TABLE TICKET_TRACK 
(
  IDTICKET_TRACK NUMBER NOT NULL 
, IDTICKET NUMBER 
, FECHA_HORA DATE 
, IDOPERADOR NUMBER 
, IDESTADO NUMBER 
, CONSTRAINT TICKET_TRACK_PK PRIMARY KEY 
  (
    IDTICKET_TRACK 
  )
  ENABLE 
);


-- Creación de índice de tracking por ticket
CREATE INDEX TICKET_TRACK_BY_TICKET ON TICKET_TRACK (IDTICKET);

CREATE SEQUENCE  "IASSIST"."SEQ_TICKET_TRACK"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;

ALTER TABLE IASSIST.TICKET_TRACK ADD OBJECTHASH VARCHAR2(50);

