
CREATE TABLE IASSIST.COLORES 
(
  IDCOLOR NUMBER NOT NULL 
, NOMBRE VARCHAR2(255) 
, CONSTRAINT COLORES_PK PRIMARY KEY 
  (
    IDCOLOR 
  )
  ENABLE 
);

ALTER TABLE IASSIST.COLORES ADD OBJECTHASH VARCHAR2(50 BYTE);


ALTER TABLE IASSIST.TICKETS ADD IDCOLOR NUMBER;

ALTER TABLE IASSIST.TICKETS ADD 
CONSTRAINT "TICKETS_COLORES_FK" FOREIGN KEY ("IDCOLOR")
	  REFERENCES "IASSIST"."COLORES" ("IDCOLOR") ENABLE;


	        
ALTER TABLE IASSIST.TICKETS
ADD (IDPROBLEMA NUMBER);

ALTER TABLE IASSIST.TICKETS ADD CONSTRAINT "TICKET_PROBLEMA_FK" FOREIGN KEY ("IDPROBLEMA")
	  REFERENCES "IASSIST"."PROBLEMAS" ("IDPROBLEMA") ENABLE;
      
UPDATE IASSIST.TICKETS A
SET A.IDPROBLEMA = (SELECT Z.IDPROBLEMA FROM IASSIST.TICKET_PRESTADORES Z WHERE Z.IDTICKETPRESTADOR = (SELECT MIN(IDTICKETPRESTADOR) FROM IASSIST.TICKET_PRESTADORES WHERE IDTICKET = Z.IDTICKET) AND Z.IDTICKET = A.IDTICKET);

COMMIT;

UPDATE IASSIST.TICKET_PRESTADORES
SET IDPROBLEMA = NULL;

COMMIT;

ALTER TABLE IASSIST.TICKET_PRESTADORES DROP COLUMN IDPROBLEMA;


INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (1, 'NEGRO');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (2,'BLANCO');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (3,'AZUL');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (4,'AMARILLO');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (5,'ROJO');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (6,'VERDE');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (7,'GRIS');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (8,'CELESTE');

INSERT INTO COLORES (IDCOLOR, NOMBRE) VALUES (9,'NARANJA');

COMMIT;

