--------------------------------------------------------
--  DDL for Package TICKET_PKG
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "IASSIST"."TICKET_PKG" AS 

  TYPE tyRefCursor is ref cursor;
  INT_NULL CONSTANT NUMBER:= -1;
    
  PROCEDURE GET_TICKET_BY_ID
  (
      P_ID IN prestadores.idprestador%TYPE,
      P_OBJECTHASH IN prestadores.objecthash%TYPE,
      R_CURSOR OUT tyRefCursor
  );
  
  PROCEDURE LIST_TICKET
  (
      P_ID IN tickets.idticket%TYPE,
      P_IDOPERADOR IN tickets.idoperador%TYPE,
      P_IDAFILIADO IN tickets.idafiliado%TYPE,
      P_CIUDAD_ORIGEN IN tickets.idciudad_origen%TYPE,
      P_CIUDAD_DESTINO IN tickets.idciudad_destino%TYPE,
      P_SEARCH IN varchar2,
      P_IS_PAGED IN number,
      P_PAGE_START IN number,
      P_PAGE_SIZE IN number,
      P_ORDER_BY IN varchar2,
      R_CURSOR OUT tyRefCursor
  );
  
  PROCEDURE CREATE_TICKET (
    P_ID OUT tickets.idticket%TYPE,
    P_IDOPERADOR IN tickets.idoperador%TYPE,
    P_ID_PAIS_ORIGEN IN tickets.idpais_origen%TYPE,
    P_IDAFILIADO IN tickets.idafiliado%TYPE,
    P_TELEFONO IN tickets.telefono%TYPE,
    P_IDESTADO IN tickets.idestado%TYPE,
    P_ID_PAIS_DESTINO IN tickets.idpais_destino%TYPE,
    P_ID_PROV_ORIGEN IN tickets.idprovincia_origen%TYPE,
    P_ID_PROV_DEST IN tickets.idprovincia_destino%TYPE,
    P_CIUDAD_ORIGEN IN tickets.idciudad_origen%TYPE,
    P_CIUDAD_DEST IN tickets.idciudad_destino%TYPE,
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    P_CALLE_ORIGEN IN tickets.calle_origen%TYPE,
    -- EGV 25May2017 Inicio
    --P_ALTURA_ORIGEN IN tickets.altura_origen%TYPE,
    -- EGV 25May2017 Fin
    P_CALLE_DESTINO IN tickets.calle_destino%TYPE,
    -- EGV 25May2017 Inicio
    --P_ALTURA_DESTINO IN tickets.altura_destino%TYPE,
    -- EGV 25May2017 Fin
    P_IDLOCALIDA_ORIGEN IN tickets.idlocalidad_origen%TYPE,
    P_IDLOCALIDA_DESTINO IN tickets.idlocalidad_destino%TYPE,
    -- EGV 25May2017 Inicio
    --P_IDPROBLEMA IN tickets.idproblema%TYPE,
    -- EGV 25May2017 Fin
    P_TIPO_TICKET IN tickets.tipo_ticket%TYPE
    -- EGV 20Jun2017 Inicio
    ,P_OKAFILIADO IN tickets.okafiliado%TYPE
    ,P_CANT_TICKETS_AFIL in tickets.cant_tickets_afil%TYPE
    -- EGV 20Jun2017 Fin
    
  );
  
  PROCEDURE MODIFY_TICKET 
  (
    P_ID IN tickets.idticket%TYPE,
    P_IDOPERADOR IN tickets.idoperador%TYPE,
    P_IDAFILIADO IN tickets.idafiliado%TYPE,
    P_ID_PAIS_ORIGEN IN tickets.idpais_origen%TYPE,
    P_ID_PROV_ORIGEN IN tickets.idprovincia_origen%TYPE,
    P_CIUDAD_ORIGEN IN tickets.idciudad_origen%TYPE,
    P_ID_PAIS_DEST IN tickets.idpais_destino%TYPE,
    P_ID_PROV_DEST IN tickets.idprovincia_destino%TYPE,
    P_CIUDAD_DEST IN tickets.idciudad_destino%TYPE,
    P_TELEFONO IN tickets.telefono%TYPE,
    P_IDESTADO IN tickets.idestado%TYPE,
    P_CALLE_ORIGEN IN tickets.calle_origen%TYPE,
    -- EGV 25May2017 Inicio
    --P_ALTURA_ORIGEN IN tickets.altura_origen%TYPE,
    -- EGV 25May2017 Fin
    P_CALLE_DESTINO IN tickets.calle_destino%TYPE,
    -- EGV 25May2017 Inicio
    --P_ALTURA_DESTINO IN tickets.altura_destino%TYPE,
    -- EGV 25May2017 Fin
    P_ID_LOCALIDAD_DESTINO IN tickets.idprovincia_destino%TYPE,
    P_ID_LOCALIDAD_ORIGEN IN tickets.idlocalidad_origen%TYPE, 
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    -- EGV 25May2017 Inicio
    --P_IDPROBLEMA IN tickets.idproblema%TYPE,
    -- EGV 25May2017 Fin
    P_TIPO_TICKET IN tickets.tipo_ticket%TYPE,
    -- EGV 20Jun2017 Inicio
    P_OKAFILIADO IN tickets.okafiliado%TYPE,
    P_CANT_TICKETS_AFIL in tickets.cant_tickets_afil%TYPE,
    -- EGV 20Jun2017 Fin
    P_AFFECTED_ROWS OUT number
  );
  
  PROCEDURE DELETE_TICKET_PRESTADOR (
    P_ID IN TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE
  );
  
  PROCEDURE DELETE_PRESTADOR_BY_TICKET (
    P_IDTICKET IN TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE
  );
  
    -- Relacion ticket-prestador.  
    PROCEDURE CREATE_TICKET_PRESTADOR (
    P_ID OUT TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE,
    P_IDTICKET IN NUMBER, 
    P_IDPRESTADOR IN NUMBER,
    P_IDTIPOSERVICIO IN NUMBER,
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    P_COMENTARIOS IN TICKET_PRESTADORES.COMENTARIOS%TYPE,
    P_KILOMETROS IN TICKET_PRESTADORES.KILOMETROS%TYPE,
    P_COSTO IN TICKET_PRESTADORES.COSTO%TYPE
    -- EGV 25May2017 Inicio
    ,P_IDPROBLEMA IN TICKET_PRESTADORES.IDPROBLEMA%TYPE,
    P_IDPAIS_ORIGEN IN TICKET_PRESTADORES.IDPAIS_ORIGEN%TYPE, 
	P_IDPAIS_DESTINO IN TICKET_PRESTADORES.IDPAIS_DESTINO%TYPE, 
	P_IDPROVINCIA_ORIGEN IN TICKET_PRESTADORES.IDPROVINCIA_ORIGEN%TYPE, 
	P_IDPROVINCIA_DESTINO IN TICKET_PRESTADORES.IDPROVINCIA_DESTINO%TYPE, 
	P_IDCIUDAD_ORIGEN IN TICKET_PRESTADORES.IDCIUDAD_ORIGEN%TYPE, 
	P_IDCIUDAD_DESTINO IN TICKET_PRESTADORES.IDCIUDAD_DESTINO%TYPE, 
	P_CALLE_ORIGEN IN TICKET_PRESTADORES.CALLE_ORIGEN%TYPE, 
	P_IDLOCALIDAD_ORIGEN IN TICKET_PRESTADORES.IDLOCALIDAD_ORIGEN%TYPE, 
	P_IDLOCALIDAD_DESTINO IN TICKET_PRESTADORES.IDLOCALIDAD_DESTINO%TYPE, 
	P_CALLE_DESTINO IN TICKET_PRESTADORES.CALLE_DESTINO%TYPE,
    P_IDESTADO IN TICKET_PRESTADORES.IDESTADO%TYPE,
    P_IDTICKETPRESTADOR_RETRABAJO IN TICKET_PRESTADORES.IDTICKETPRESTADOR_RETRABAJO%TYPE,
	P_DEMORA IN TICKET_PRESTADORES.DEMORA%TYPE, 
	P_PATENTE IN TICKET_PRESTADORES.PATENTE%TYPE, 
	P_NOMBRE_CHOFER IN TICKET_PRESTADORES.NOMBRE_CHOFER%TYPE
    -- EGV 25May2017 Fin   
    -- EGV 20Jun2017 Inicio
    ,P_IDFINALIZACION IN TICKET_PRESTADORES.IDFINALIZACION%TYPE
    -- EGV 20Jun2017 Fin
  );  
  
    PROCEDURE MODIFY_TICKET_PRESTADOR (
    P_ID IN TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE,
    P_IDTICKET IN NUMBER, 
    P_IDPRESTADOR IN NUMBER,
    P_IDTIPOSERVICIO IN NUMBER,
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    P_COMENTARIOS IN TICKET_PRESTADORES.COMENTARIOS%TYPE,
    P_KILOMETROS IN TICKET_PRESTADORES.KILOMETROS%TYPE,
    P_COSTO IN TICKET_PRESTADORES.COSTO%TYPE,
    -- EGV 25May2017 Inicio
    P_IDPROBLEMA IN TICKET_PRESTADORES.IDPROBLEMA%TYPE,
    P_IDPAIS_ORIGEN IN TICKET_PRESTADORES.IDPAIS_ORIGEN%TYPE, 
	P_IDPAIS_DESTINO IN TICKET_PRESTADORES.IDPAIS_DESTINO%TYPE, 
	P_IDPROVINCIA_ORIGEN IN TICKET_PRESTADORES.IDPROVINCIA_ORIGEN%TYPE, 
	P_IDPROVINCIA_DESTINO IN TICKET_PRESTADORES.IDPROVINCIA_DESTINO%TYPE, 
	P_IDCIUDAD_ORIGEN IN TICKET_PRESTADORES.IDCIUDAD_ORIGEN%TYPE, 
	P_IDCIUDAD_DESTINO IN TICKET_PRESTADORES.IDCIUDAD_DESTINO%TYPE, 
	P_CALLE_ORIGEN IN TICKET_PRESTADORES.CALLE_ORIGEN%TYPE, 
	P_IDLOCALIDAD_ORIGEN IN TICKET_PRESTADORES.IDLOCALIDAD_ORIGEN%TYPE, 
	P_IDLOCALIDAD_DESTINO IN TICKET_PRESTADORES.IDLOCALIDAD_DESTINO%TYPE, 
	P_CALLE_DESTINO IN TICKET_PRESTADORES.CALLE_DESTINO%TYPE,
    P_IDESTADO IN TICKET_PRESTADORES.IDESTADO%TYPE,
    P_IDTICKETPRESTADOR_RETRABAJO IN TICKET_PRESTADORES.IDTICKETPRESTADOR_RETRABAJO%TYPE,
	P_DEMORA IN TICKET_PRESTADORES.DEMORA%TYPE, 
	P_PATENTE IN TICKET_PRESTADORES.PATENTE%TYPE, 
	P_NOMBRE_CHOFER IN TICKET_PRESTADORES.NOMBRE_CHOFER%TYPE,
    -- EGV 25May2017 Fin       
        -- EGV 20Jun2017 Inicio
    P_IDFINALIZACION IN TICKET_PRESTADORES.IDFINALIZACION%TYPE,
    -- EGV 20Jun2017 Fin
    P_AFFECTED_ROWS OUT number
  );
  

PROCEDURE LIST_PRESTADORES_BY_TICKET (P_IDTICKET IN TICKET_PRESTADORES.IDTICKET%TYPE,
                                        R_CURSOR OUT tyRefCursor);
                                        
END TICKET_PKG;

/
