--------------------------------------------------------
--  DDL for Package TICKET_PKG
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "IASSIST"."TICKET_PKG" AS 

  TYPE tyRefCursor is ref cursor;
  INT_NULL CONSTANT NUMBER:= -1;
    
  PROCEDURE GET_TICKET_BY_ID
  (
      P_ID IN prestadores.idprestador%TYPE,
      P_OBJECTHASH IN prestadores.objecthash%TYPE,
      R_CURSOR OUT tyRefCursor
  );
  
  PROCEDURE LIST_TICKET
  (
      P_ID IN tickets.idticket%TYPE,
      P_IDOPERADOR IN tickets.idoperador%TYPE,
      P_IDAFILIADO IN tickets.idafiliado%TYPE,
      P_CIUDAD_ORIGEN IN tickets.idciudad_origen%TYPE,
      P_CIUDAD_DESTINO IN tickets.idciudad_destino%TYPE,
      P_SEARCH IN varchar2,
      P_IS_PAGED IN number,
      P_PAGE_START IN number,
      P_PAGE_SIZE IN number,
      P_ORDER_BY IN varchar2,
      R_CURSOR OUT tyRefCursor
  );
  
  PROCEDURE CREATE_TICKET (
    P_ID OUT tickets.idticket%TYPE,
    P_IDOPERADOR IN tickets.idoperador%TYPE,
    P_ID_PAIS_ORIGEN IN tickets.idpais_origen%TYPE,
    P_IDAFILIADO IN tickets.idafiliado%TYPE,
    P_TELEFONO IN tickets.telefono%TYPE,
    P_IDESTADO IN tickets.idestado%TYPE,
    P_ID_PAIS_DESTINO IN tickets.idpais_destino%TYPE,
    P_ID_PROV_ORIGEN IN tickets.idprovincia_origen%TYPE,
    P_ID_PROV_DEST IN tickets.idprovincia_destino%TYPE,
    P_CIUDAD_ORIGEN IN tickets.idciudad_origen%TYPE,
    P_CIUDAD_DEST IN tickets.idciudad_destino%TYPE,
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    P_CALLE_ORIGEN IN tickets.calle_origen%TYPE,
    P_CALLE_DESTINO IN tickets.calle_destino%TYPE,
    P_IDLOCALIDA_ORIGEN IN tickets.idlocalidad_origen%TYPE,
    P_IDLOCALIDA_DESTINO IN tickets.idlocalidad_destino%TYPE,
    P_TIPO_TICKET IN tickets.tipo_ticket%TYPE,
    P_OKAFILIADO IN tickets.okafiliado%TYPE,
    P_CANT_TICKETS_AFIL in tickets.cant_tickets_afil%TYPE,
    P_IDCOLOR in tickets.idcolor%TYPE,
    P_IDPROBLEMA in tickets.idproblema%TYPE,
    P_UBICACION_DESCR IN tickets.ubicacion_descr%TYPE,
    P_DEMORA_EST In tickets.demora_est%TYPE,
    P_URL_ORIGEN In tickets.url_origen%TYPE,
    P_URL_DESTINO In tickets.url_destino%TYPE
  );
  
  PROCEDURE MODIFY_TICKET 
  (
    P_ID IN tickets.idticket%TYPE,
    P_IDOPERADOR IN tickets.idoperador%TYPE,
    P_IDAFILIADO IN tickets.idafiliado%TYPE,
    P_ID_PAIS_ORIGEN IN tickets.idpais_origen%TYPE,
    P_ID_PROV_ORIGEN IN tickets.idprovincia_origen%TYPE,
    P_CIUDAD_ORIGEN IN tickets.idciudad_origen%TYPE,
    P_ID_PAIS_DEST IN tickets.idpais_destino%TYPE,
    P_ID_PROV_DEST IN tickets.idprovincia_destino%TYPE,
    P_CIUDAD_DEST IN tickets.idciudad_destino%TYPE,
    P_TELEFONO IN tickets.telefono%TYPE,
    P_IDESTADO IN tickets.idestado%TYPE,
    P_CALLE_ORIGEN IN tickets.calle_origen%TYPE,
    P_CALLE_DESTINO IN tickets.calle_destino%TYPE,
    P_ID_LOCALIDAD_DESTINO IN tickets.idprovincia_destino%TYPE,
    P_ID_LOCALIDAD_ORIGEN IN tickets.idlocalidad_origen%TYPE, 
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    P_TIPO_TICKET IN tickets.tipo_ticket%TYPE,
    P_OKAFILIADO IN tickets.okafiliado%TYPE,
    P_CANT_TICKETS_AFIL in tickets.cant_tickets_afil%TYPE,
    P_IDCOLOR in tickets.idcolor%TYPE,
    P_IDPROBLEMA in tickets.idproblema%TYPE,
    P_UBICACION_DESCR IN tickets.ubicacion_descr%TYPE,
    P_DEMORA_EST In tickets.demora_est%TYPE,
    P_URL_ORIGEN In tickets.url_origen%TYPE,
    P_URL_DESTINO In tickets.url_destino%TYPE,
    P_AFFECTED_ROWS OUT number
  );
  
  PROCEDURE DELETE_TICKET_PRESTADOR (
    P_ID IN TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE
  );
  
  PROCEDURE DELETE_PRESTADOR_BY_TICKET (
    P_IDTICKET IN TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE
  );
  
    -- Relacion ticket-prestador.  
PROCEDURE CREATE_TICKET_PRESTADOR (
    P_ID OUT TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE,
    P_IDTICKET IN NUMBER, 
    P_IDPRESTADOR IN NUMBER,
    P_IDTIPOSERVICIO IN NUMBER,
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    P_COMENTARIOS IN TICKET_PRESTADORES.COMENTARIOS%TYPE,
    P_KILOMETROS IN TICKET_PRESTADORES.KILOMETROS%TYPE,
    P_COSTO IN TICKET_PRESTADORES.COSTO%TYPE,
    P_IDPAIS_ORIGEN IN TICKET_PRESTADORES.IDPAIS_ORIGEN%TYPE, 
	P_IDPAIS_DESTINO IN TICKET_PRESTADORES.IDPAIS_DESTINO%TYPE, 
	P_IDPROVINCIA_ORIGEN IN TICKET_PRESTADORES.IDPROVINCIA_ORIGEN%TYPE, 
	P_IDPROVINCIA_DESTINO IN TICKET_PRESTADORES.IDPROVINCIA_DESTINO%TYPE, 
	P_IDCIUDAD_ORIGEN IN TICKET_PRESTADORES.IDCIUDAD_ORIGEN%TYPE, 
	P_IDCIUDAD_DESTINO IN TICKET_PRESTADORES.IDCIUDAD_DESTINO%TYPE, 
	P_CALLE_ORIGEN IN TICKET_PRESTADORES.CALLE_ORIGEN%TYPE, 
	P_IDLOCALIDAD_ORIGEN IN TICKET_PRESTADORES.IDLOCALIDAD_ORIGEN%TYPE, 
	P_IDLOCALIDAD_DESTINO IN TICKET_PRESTADORES.IDLOCALIDAD_DESTINO%TYPE, 
	P_CALLE_DESTINO IN TICKET_PRESTADORES.CALLE_DESTINO%TYPE,
    P_IDESTADO IN TICKET_PRESTADORES.IDESTADO%TYPE,
    P_IDTICKETPRESTADOR_RETRABAJO IN TICKET_PRESTADORES.IDTICKETPRESTADOR_RETRABAJO%TYPE,
	P_PATENTE IN TICKET_PRESTADORES.PATENTE%TYPE, 
	P_NOMBRE_CHOFER IN TICKET_PRESTADORES.NOMBRE_CHOFER%TYPE,
    P_IDFINALIZACION IN TICKET_PRESTADORES.IDFINALIZACION%TYPE,
    P_DEMORA_EST In TICKET_PRESTADORES.DEMORA_EST%TYPE,
    P_DEMORA_REAL In TICKET_PRESTADORES.DEMORA_REAL%TYPE,
    P_IDTIPOPRESTACION In TICKET_PRESTADORES.IDTIPOPRESTACION%TYPE
  );  
  
PROCEDURE MODIFY_TICKET_PRESTADOR (
    P_ID IN TICKET_PRESTADORES.IDTICKETPRESTADOR%TYPE,
    P_IDTICKET IN NUMBER, 
    P_IDPRESTADOR IN NUMBER,
    P_IDTIPOSERVICIO IN NUMBER,
    P_OBJECTHASH IN PRESTADORES.objecthash%TYPE,
    P_COMENTARIOS IN TICKET_PRESTADORES.COMENTARIOS%TYPE,
    P_KILOMETROS IN TICKET_PRESTADORES.KILOMETROS%TYPE,
    P_COSTO IN TICKET_PRESTADORES.COSTO%TYPE,
    P_IDPAIS_ORIGEN IN TICKET_PRESTADORES.IDPAIS_ORIGEN%TYPE, 
	P_IDPAIS_DESTINO IN TICKET_PRESTADORES.IDPAIS_DESTINO%TYPE, 
	P_IDPROVINCIA_ORIGEN IN TICKET_PRESTADORES.IDPROVINCIA_ORIGEN%TYPE, 
	P_IDPROVINCIA_DESTINO IN TICKET_PRESTADORES.IDPROVINCIA_DESTINO%TYPE, 
	P_IDCIUDAD_ORIGEN IN TICKET_PRESTADORES.IDCIUDAD_ORIGEN%TYPE, 
	P_IDCIUDAD_DESTINO IN TICKET_PRESTADORES.IDCIUDAD_DESTINO%TYPE, 
	P_CALLE_ORIGEN IN TICKET_PRESTADORES.CALLE_ORIGEN%TYPE, 
	P_IDLOCALIDAD_ORIGEN IN TICKET_PRESTADORES.IDLOCALIDAD_ORIGEN%TYPE, 
	P_IDLOCALIDAD_DESTINO IN TICKET_PRESTADORES.IDLOCALIDAD_DESTINO%TYPE, 
	P_CALLE_DESTINO IN TICKET_PRESTADORES.CALLE_DESTINO%TYPE,
    P_IDESTADO IN TICKET_PRESTADORES.IDESTADO%TYPE,
    P_IDTICKETPRESTADOR_RETRABAJO IN TICKET_PRESTADORES.IDTICKETPRESTADOR_RETRABAJO%TYPE,
	P_PATENTE IN TICKET_PRESTADORES.PATENTE%TYPE, 
	P_NOMBRE_CHOFER IN TICKET_PRESTADORES.NOMBRE_CHOFER%TYPE,
    P_IDFINALIZACION IN TICKET_PRESTADORES.IDFINALIZACION%TYPE,
    P_DEMORA_EST In TICKET_PRESTADORES.DEMORA_EST%TYPE,
    P_DEMORA_REAL In TICKET_PRESTADORES.DEMORA_REAL%TYPE,
    P_IDTIPOPRESTACION In TICKET_PRESTADORES.IDTIPOPRESTACION%TYPE,
    P_AFFECTED_ROWS OUT number
  );
  

PROCEDURE LIST_PRESTADORES_BY_TICKET (P_IDTICKET IN TICKET_PRESTADORES.IDTICKET%TYPE,
                                        R_CURSOR OUT tyRefCursor);
                                        

                                     
PROCEDURE LIST_TICKET_TRACK_BY_TICKET(P_IDTICKET IN TICKET_TRACK.IDTICKET%TYPE, R_CURSOR OUT tyRefCursor);   

PROCEDURE CREATE_TICKET_TRACK (
    P_ID OUT ticket_track.idticket_track%TYPE,
    P_IDTICKET IN ticket_track.idticket%TYPE,
    P_IDOPERADOR IN ticket_track.idoperador%TYPE,
    P_IDESTADO IN ticket_track.idestado%TYPE,
    P_OBJECTHASH IN ticket_track.objecthash%TYPE
  );
                                        
END TICKET_PKG;

/
