//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.InterAssist {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.InterAssist.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string BTN_ACEPTAR {
            get {
                return ResourceManager.GetString("BTN_ACEPTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Prestador.
        /// </summary>
        internal static string BTN_ASIGNAR_PRESTADOR {
            get {
                return ResourceManager.GetString("BTN_ASIGNAR_PRESTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string BTN_BUSCAR {
            get {
                return ResourceManager.GetString("BTN_BUSCAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Clave.
        /// </summary>
        internal static string BTN_CAMBIAR_CLAVE {
            get {
                return ResourceManager.GetString("BTN_CAMBIAR_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string BTN_CANCELAR {
            get {
                return ResourceManager.GetString("BTN_CANCELAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo Afiliado.
        /// </summary>
        internal static string BTN_CREAR_AFILIADO {
            get {
                return ResourceManager.GetString("BTN_CREAR_AFILIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo Prestador.
        /// </summary>
        internal static string BTN_CREAR_NUEVO_PRESTADOR {
            get {
                return ResourceManager.GetString("BTN_CREAR_NUEVO_PRESTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Nuevo Usuario.
        /// </summary>
        internal static string BTN_CREAR_USUARIO {
            get {
                return ResourceManager.GetString("BTN_CREAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar.
        /// </summary>
        internal static string BTN_FREE_SEARCH {
            get {
                return ResourceManager.GetString("BTN_FREE_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        internal static string BTN_GRID_MODIFICAR {
            get {
                return ResourceManager.GetString("BTN_GRID_MODIFICAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar y Salir.
        /// </summary>
        internal static string BTN_GUARDAR_Y_SALIR {
            get {
                return ResourceManager.GetString("BTN_GUARDAR_Y_SALIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        internal static string BTN_INICIAR_SESION {
            get {
                return ResourceManager.GetString("BTN_INICIAR_SESION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string BTN_LOGOUT {
            get {
                return ResourceManager.GetString("BTN_LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AFILIADOS.
        /// </summary>
        internal static string BTN_MENU_AFILIADOS {
            get {
                return ResourceManager.GetString("BTN_MENU_AFILIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASOS.
        /// </summary>
        internal static string BTN_MENU_CASOS {
            get {
                return ResourceManager.GetString("BTN_MENU_CASOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERADORES.
        /// </summary>
        internal static string BTN_MENU_OPERADORES {
            get {
                return ResourceManager.GetString("BTN_MENU_OPERADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESTADORES.
        /// </summary>
        internal static string BTN_MENU_PRESTADORES {
            get {
                return ResourceManager.GetString("BTN_MENU_PRESTADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORTES.
        /// </summary>
        internal static string BTN_MENU_REPORTES {
            get {
                return ResourceManager.GetString("BTN_MENU_REPORTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATOS.
        /// </summary>
        internal static string BTN_MENU_UPLODAS {
            get {
                return ResourceManager.GetString("BTN_MENU_UPLODAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar.
        /// </summary>
        internal static string BTN_PRESTADOR_ASIGNAR {
            get {
                return ResourceManager.GetString("BTN_PRESTADOR_ASIGNAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string BTN_PRESTADOR_INFO {
            get {
                return ResourceManager.GetString("BTN_PRESTADOR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitar Prestador.
        /// </summary>
        internal static string BTN_QUITAR_PRESTADOR {
            get {
                return ResourceManager.GetString("BTN_QUITAR_PRESTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar Clave.
        /// </summary>
        internal static string BTN_REINICIAR_PASSWORD {
            get {
                return ResourceManager.GetString("BTN_REINICIAR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        internal static string BTN_VER {
            get {
                return ResourceManager.GetString("BTN_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver.
        /// </summary>
        internal static string BTN_VOLVER {
            get {
                return ResourceManager.GetString("BTN_VOLVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string CHK_ADMIN {
            get {
                return ResourceManager.GetString("CHK_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string CHK_ESTADO {
            get {
                return ResourceManager.GetString("CHK_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string DECIMAL_SEPARATOR {
            get {
                return ResourceManager.GetString("DECIMAL_SEPARATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave anterior no es correcta.
        /// </summary>
        internal static string ERR_CLAVE_ANTERIOR {
            get {
                return ResourceManager.GetString("ERR_CLAVE_ANTERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe ser una dirección de email.
        /// </summary>
        internal static string ERR_FIELD_EMAIL {
            get {
                return ResourceManager.GetString("ERR_FIELD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0}  debe ser numérico de 4 dígitos.
        /// </summary>
        internal static string ERR_FORMATO_AÑO {
            get {
                return ResourceManager.GetString("ERR_FORMATO_AÑO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no es correcto.
        /// </summary>
        internal static string ERR_GENERIC_CMB {
            get {
                return ResourceManager.GetString("ERR_GENERIC_CMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no puede ser vacío.
        /// </summary>
        internal static string ERR_LOGIN_EMPTY_PASSWORD {
            get {
                return ResourceManager.GetString("ERR_LOGIN_EMPTY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no puede ser vacío.
        /// </summary>
        internal static string ERR_LOGIN_EMPTY_USER {
            get {
                return ResourceManager.GetString("ERR_LOGIN_EMPTY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} o {1} no son correctos.
        /// </summary>
        internal static string ERR_LOGIN_FAIL {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} no está activo en el sistema.
        /// </summary>
        internal static string ERR_LOGIN_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_LOGIN_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} debe tener al menos {1} caracteres.
        /// </summary>
        internal static string ERR_LONG_PASSWORD {
            get {
                return ResourceManager.GetString("ERR_LONG_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} debe tener entre {1} y {2} caracteres.
        /// </summary>
        internal static string ERR_LONG_USUARIO {
            get {
                return ResourceManager.GetString("ERR_LONG_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los campos {0} y {1} deben ser iguales.
        /// </summary>
        internal static string ERR_PASSWORD_COMPARE {
            get {
                return ResourceManager.GetString("ERR_PASSWORD_COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La póliza ya existe en el sistema.
        /// </summary>
        internal static string ERR_POLIZA_EXISTENTE {
            get {
                return ResourceManager.GetString("ERR_POLIZA_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe asignar un prestador al caso.
        /// </summary>
        internal static string ERR_PRESTADOR_OBLIGATORIO {
            get {
                return ResourceManager.GetString("ERR_PRESTADOR_OBLIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe elegir una opción para el combo {0}.
        /// </summary>
        internal static string ERR_REQUEST_COMBO {
            get {
                return ResourceManager.GetString("ERR_REQUEST_COMBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo {0} no puede ser vacío.
        /// </summary>
        internal static string ERR_REQUEST_FIELD {
            get {
                return ResourceManager.GetString("ERR_REQUEST_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} ya existe en el sistema..
        /// </summary>
        internal static string ERR_USUARIO_EXISTENTE {
            get {
                return ResourceManager.GetString("ERR_USUARIO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string LBL_AFIILIADO_EMPRESA {
            get {
                return ResourceManager.GetString("LBL_AFIILIADO_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string LBL_AFILIADO_ANO {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_ANO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string LBL_AFILIADO_APELLIDO {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_APELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string LBL_AFILIADO_CATEGORIA {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_CATEGORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        internal static string LBL_AFILIADO_CODIGO_POSTAL {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_CODIGO_POSTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string LBL_AFILIADO_COLOR {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string LBL_AFILIADO_DIRECCION {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_DIRECCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento.
        /// </summary>
        internal static string LBL_AFILIADO_DOCUMENTO {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_DOCUMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string LBL_AFILIADO_ESTADO {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Desde.
        /// </summary>
        internal static string LBL_AFILIADO_FECHA_DESDE {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_FECHA_DESDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Hasta.
        /// </summary>
        internal static string LBL_AFILIADO_FECHA_HASTA {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_FECHA_HASTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobertura Hogar.
        /// </summary>
        internal static string LBL_AFILIADO_HOGAR {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_HOGAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LBL_AFILIADO_ID {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca.
        /// </summary>
        internal static string LBL_AFILIADO_MARCA {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_MARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        internal static string LBL_AFILIADO_MODELO {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_MODELO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string LBL_AFILIADO_NOMBRE {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Caso.
        /// </summary>
        internal static string LBL_AFILIADO_NUEVO_CASO {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_NUEVO_CASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Póliza.
        /// </summary>
        internal static string LBL_AFILIADO_POLIZA {
            get {
                return ResourceManager.GetString("LBL_AFILIADO_POLIZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente.
        /// </summary>
        internal static string LBL_AFILIAFO_PATENTE {
            get {
                return ResourceManager.GetString("LBL_AFILIAFO_PATENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string LBL_CASO_DETALLES {
            get {
                return ResourceManager.GetString("LBL_CASO_DETALLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historicos.
        /// </summary>
        internal static string LBL_CASO_HISTORICO {
            get {
                return ResourceManager.GetString("LBL_CASO_HISTORICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LBL_CASO_ID {
            get {
                return ResourceManager.GetString("LBL_CASO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string LBL_OPERADOR_ACTIVO {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string LBL_OPERADOR_ADMIN {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string LBL_OPERADOR_APELLIDO {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_APELLIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        internal static string LBL_OPERADOR_CLAVE {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave Anterior.
        /// </summary>
        internal static string LBL_OPERADOR_CLAVE_ANTERIOR {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_CLAVE_ANTERIOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LBL_OPERADOR_EMAIL {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LBL_OPERADOR_ID {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string LBL_OPERADOR_NOMBRE {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Clave.
        /// </summary>
        internal static string LBL_OPERADOR_RE_CLAVE {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_RE_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string LBL_OPERADOR_USUARIO {
            get {
                return ResourceManager.GetString("LBL_OPERADOR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva Clave.
        /// </summary>
        internal static string LBL_OPERADORE_NUEVA_CLAVE {
            get {
                return ResourceManager.GetString("LBL_OPERADORE_NUEVA_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string LBL_PRESTADOR_ACTIVO {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        internal static string LBL_PRESTADOR_CELULAR {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_CELULAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular2.
        /// </summary>
        internal static string LBL_PRESTADOR_CELULAR2 {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_CELULAR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string LBL_PRESTADOR_CIUDAD {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_CIUDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUIT.
        /// </summary>
        internal static string LBL_PRESTADOR_CIUT {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_CIUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string LBL_PRESTADOR_DESCRIPCION {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio.
        /// </summary>
        internal static string LBL_PRESTADOR_DOMICILIO {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_DOMICILIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LBL_PRESTADOR_EMAIL {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string LBL_PRESTADOR_ESTADO {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LBL_PRESTADOR_ID {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA.
        /// </summary>
        internal static string LBL_PRESTADOR_IVA {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_IVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KM.
        /// </summary>
        internal static string LBL_PRESTADOR_KM {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liv.
        /// </summary>
        internal static string LBL_PRESTADOR_LIV {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_LIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        internal static string LBL_PRESTADOR_LOCALIDAD {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_LOCALIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movida.
        /// </summary>
        internal static string LBL_PRESTADOR_MOVIDA {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_MOVIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NextTel.
        /// </summary>
        internal static string LBL_PRESTADOR_NEXT_TEX {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_NEXT_TEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string LBL_PRESTADOR_NOMBRE {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_NOMBRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pais.
        /// </summary>
        internal static string LBL_PRESTADOR_PAIS {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_PAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string LBL_PRESTADOR_PROVINCIA {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_PROVINCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS1.
        /// </summary>
        internal static string LBL_PRESTADOR_PS1 {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_PS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS2.
        /// </summary>
        internal static string LBL_PRESTADOR_PS2 {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_PS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP1.
        /// </summary>
        internal static string LBL_PRESTADOR_SP1 {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_SP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2.
        /// </summary>
        internal static string LBL_PRESTADOR_SP2 {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_SP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarifas.
        /// </summary>
        internal static string LBL_PRESTADOR_TARIFAS {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_TARIFAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string LBL_PRESTADOR_TELEFONO1 {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_TELEFONO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono2.
        /// </summary>
        internal static string LBL_PRESTADOR_TELEFONO2 {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_TELEFONO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        internal static string LBL_PRESTADOR_UBICACION {
            get {
                return ResourceManager.GetString("LBL_PRESTADOR_UBICACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambio de Clave.
        /// </summary>
        internal static string LBL_SECCION_CAMBIO_CLAVE {
            get {
                return ResourceManager.GetString("LBL_SECCION_CAMBIO_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destino.
        /// </summary>
        internal static string LBL_SECCION_CASO_DESTINO {
            get {
                return ResourceManager.GetString("LBL_SECCION_CASO_DESTINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen.
        /// </summary>
        internal static string LBL_SECCION_CASO_ORIGEN {
            get {
                return ResourceManager.GetString("LBL_SECCION_CASO_ORIGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string LBL_SEPARADOR {
            get {
                return ResourceManager.GetString("LBL_SEPARADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        internal static string LBL_TICKET_COSTO {
            get {
                return ResourceManager.GetString("LBL_TICKET_COSTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Caso.
        /// </summary>
        internal static string LBL_TICKET_ESTADO {
            get {
                return ResourceManager.GetString("LBL_TICKET_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha/Hora.
        /// </summary>
        internal static string LBL_TICKET_FECHA_HORA {
            get {
                return ResourceManager.GetString("LBL_TICKET_FECHA_HORA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometros.
        /// </summary>
        internal static string LBL_TICKET_KILOMETRO {
            get {
                return ResourceManager.GetString("LBL_TICKET_KILOMETRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_EMPRESA {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_FECHA {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_ID {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc. Destino.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_LOCALIDAD_DESTINO {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_LOCALIDAD_DESTINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loc. Origen.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_LOCALIDAD_ORIGEN {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_LOCALIDAD_ORIGEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca/Modelo.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_MARCA {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_MARCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afiliado.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_NOMBRE_AFILIADO {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_NOMBRE_AFILIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_OPERADOR {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_OPERADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patente.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_PATENTE {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_PATENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poliza.
        /// </summary>
        internal static string LBL_TICKET_LISTADO_POLIZA {
            get {
                return ResourceManager.GetString("LBL_TICKET_LISTADO_POLIZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay observaciones para mostrar.
        /// </summary>
        internal static string LBL_TICKET_NON_OBSERVACIONES {
            get {
                return ResourceManager.GetString("LBL_TICKET_NON_OBSERVACIONES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo Caso.
        /// </summary>
        internal static string LBL_TICKET_NUEVO {
            get {
                return ResourceManager.GetString("LBL_TICKET_NUEVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operador.
        /// </summary>
        internal static string LBL_TICKET_OPERADOR {
            get {
                return ResourceManager.GetString("LBL_TICKET_OPERADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problema.
        /// </summary>
        internal static string LBL_TICKET_PROBLEMA {
            get {
                return ResourceManager.GetString("LBL_TICKET_PROBLEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string LBL_TICKET_TELEFONO {
            get {
                return ResourceManager.GetString("LBL_TICKET_TELEFONO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Caso.
        /// </summary>
        internal static string LBL_TICKET_TIPO {
            get {
                return ResourceManager.GetString("LBL_TICKET_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Asistencia.
        /// </summary>
        internal static string LBL_TICKET_TIPO_ASISTENCIA {
            get {
                return ResourceManager.GetString("LBL_TICKET_TIPO_ASISTENCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL ERRORES: {0}.
        /// </summary>
        internal static string LBL_TOTAL_ERRORS {
            get {
                return ResourceManager.GetString("LBL_TOTAL_ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string LBL_UBICACION_CIUDAD {
            get {
                return ResourceManager.GetString("LBL_UBICACION_CIUDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string LBL_UBICACION_DIRECCION {
            get {
                return ResourceManager.GetString("LBL_UBICACION_DIRECCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        internal static string LBL_UBICACION_LOCALIDAD {
            get {
                return ResourceManager.GetString("LBL_UBICACION_LOCALIDAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string LBL_UBICACION_PAIS {
            get {
                return ResourceManager.GetString("LBL_UBICACION_PAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia.
        /// </summary>
        internal static string LBL_UBICACION_PROVINCIA {
            get {
                return ResourceManager.GetString("LBL_UBICACION_PROVINCIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        internal static string LBL_UBICACION_UBICACION {
            get {
                return ResourceManager.GetString("LBL_UBICACION_UBICACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg. TOTALES.
        /// </summary>
        internal static string LBL_UDDATE_REG_TOTAL {
            get {
                return ResourceManager.GetString("LBL_UDDATE_REG_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg. ELIMINADOS.
        /// </summary>
        internal static string LBL_UPDATE_DELETED {
            get {
                return ResourceManager.GetString("LBL_UPDATE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles.
        /// </summary>
        internal static string LBL_UPDATE_DETALLES {
            get {
                return ResourceManager.GetString("LBL_UPDATE_DETALLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPCIÓN.
        /// </summary>
        internal static string LBL_UPDATE_ERROR_DESCRIPCION {
            get {
                return ResourceManager.GetString("LBL_UPDATE_ERROR_DESCRIPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LINEA.
        /// </summary>
        internal static string LBL_UPDATE_ERROR_FILELINE {
            get {
                return ResourceManager.GetString("LBL_UPDATE_ERROR_FILELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMACIÓN.
        /// </summary>
        internal static string LBL_UPDATE_ERROR_INFORMACION {
            get {
                return ResourceManager.GetString("LBL_UPDATE_ERROR_INFORMACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID. ERROR.
        /// </summary>
        internal static string LBL_UPDATE_ERROR_TYPE {
            get {
                return ResourceManager.GetString("LBL_UPDATE_ERROR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errores.
        /// </summary>
        internal static string LBL_UPDATE_ERRORES {
            get {
                return ResourceManager.GetString("LBL_UPDATE_ERRORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg. NUEVOS.
        /// </summary>
        internal static string LBL_UPDATE_INSERTED {
            get {
                return ResourceManager.GetString("LBL_UPDATE_INSERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg. PROCESADOS.
        /// </summary>
        internal static string LBL_UPDATE_PROCESSED {
            get {
                return ResourceManager.GetString("LBL_UPDATE_PROCESSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg. ERRORES.
        /// </summary>
        internal static string LBL_UPDATE_REC_ERR {
            get {
                return ResourceManager.GetString("LBL_UPDATE_REC_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg. ACTUALIZADOS.
        /// </summary>
        internal static string LBL_UPDATE_UPDATED {
            get {
                return ResourceManager.GetString("LBL_UPDATE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERRORES.
        /// </summary>
        internal static string LBL_UPLOAD_CANT_ERRORES {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_CANT_ERRORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMPRESA.
        /// </summary>
        internal static string LBL_UPLOAD_EMPRESA {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_EMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO.
        /// </summary>
        internal static string LBL_UPLOAD_ESTADO {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_ESTADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FALLO.
        /// </summary>
        internal static string LBL_UPLOAD_FAIL {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA.
        /// </summary>
        internal static string LBL_UPLOAD_FECHA {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIN.
        /// </summary>
        internal static string LBL_UPLOAD_FN_FECHA {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_FN_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXITO.
        /// </summary>
        internal static string LBL_UPLOAD_HIT {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_HIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LBL_UPLOAD_ID {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARCHIVO.
        /// </summary>
        internal static string LBL_UPLOAD_NOMBRE_ARCHIVO {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_NOMBRE_ARCHIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTROS.
        /// </summary>
        internal static string LBL_UPLOAD_REGISTROS {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_REGISTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMIENZO.
        /// </summary>
        internal static string LBL_UPLOAD_ST_FECHA {
            get {
                return ResourceManager.GetString("LBL_UPLOAD_ST_FECHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Clave se ha reiniciado correctamente. La nueva clave es: {0}.
        /// </summary>
        internal static string MSG_RESET_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administraci&amp;oacute;n de Afiliados.
        /// </summary>
        internal static string SECCION_ADM_AFILIADOS {
            get {
                return ResourceManager.GetString("SECCION_ADM_AFILIADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Casos.
        /// </summary>
        internal static string SECCION_ADM_CASOS {
            get {
                return ResourceManager.GetString("SECCION_ADM_CASOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Registros Huerfanos.
        /// </summary>
        internal static string SECCION_ADM_HUERFANOS {
            get {
                return ResourceManager.GetString("SECCION_ADM_HUERFANOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administraci&amp;oacute;n de Operadores.
        /// </summary>
        internal static string SECCION_ADM_OPERADORES {
            get {
                return ResourceManager.GetString("SECCION_ADM_OPERADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Prestadores.
        /// </summary>
        internal static string SECCION_ADM_PRESTADORES {
            get {
                return ResourceManager.GetString("SECCION_ADM_PRESTADORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autenticación en Sistema.
        /// </summary>
        internal static string SECCION_LOGIN {
            get {
                return ResourceManager.GetString("SECCION_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrar mi Usuarios.
        /// </summary>
        internal static string SECCION_MI_USUARIO {
            get {
                return ResourceManager.GetString("SECCION_MI_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificando Operador.
        /// </summary>
        internal static string SECCION_MODIFICACION_OPERADOR {
            get {
                return ResourceManager.GetString("SECCION_MODIFICACION_OPERADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando Nuevo Operador.
        /// </summary>
        internal static string SECCION_NUEVO_OPERADOR {
            get {
                return ResourceManager.GetString("SECCION_NUEVO_OPERADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reportes.
        /// </summary>
        internal static string SECCION_REPORTES {
            get {
                return ResourceManager.GetString("SECCION_REPORTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administración de Datos.
        /// </summary>
        internal static string SECTION_ADM_UPLOADS {
            get {
                return ResourceManager.GetString("SECTION_ADM_UPLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de actualización.
        /// </summary>
        internal static string SECTION_DETALLES_UPLOADS {
            get {
                return ResourceManager.GetString("SECTION_DETALLES_UPLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificando Afiliado.
        /// </summary>
        internal static string SESSION_MODIF_AFILIADO {
            get {
                return ResourceManager.GetString("SESSION_MODIF_AFILIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando Nuevo Afiliado.
        /// </summary>
        internal static string SESSION_NUEVO_AFILIADO {
            get {
                return ResourceManager.GetString("SESSION_NUEVO_AFILIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error al intentar cambiar la clave. Debe iniciar sesión con la credenciales existentes..
        /// </summary>
        internal static string TEXT_ERR_CAMBIO_CLAVE {
            get {
                return ResourceManager.GetString("TEXT_ERR_CAMBIO_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click aquí para ver caso {0}.
        /// </summary>
        internal static string TOOL_TIP_ID_CASO {
            get {
                return ResourceManager.GetString("TOOL_TIP_ID_CASO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string TXT_ACTIVO {
            get {
                return ResourceManager.GetString("TXT_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string TXT_BOOL_FALSE {
            get {
                return ResourceManager.GetString("TXT_BOOL_FALSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string TXT_BOOL_TRUE {
            get {
                return ResourceManager.GetString("TXT_BOOL_TRUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los campos.
        /// </summary>
        internal static string TXT_BUSQUEDA_AVANZADA {
            get {
                return ResourceManager.GetString("TXT_BUSQUEDA_AVANZADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string TXT_BUSQUEDA_ID {
            get {
                return ResourceManager.GetString("TXT_BUSQUEDA_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se puede modificar el objeto. Es posible que otro usuario lo esté modificando en este momento. Intente en otro momento..
        /// </summary>
        internal static string TXT_CASO_ERROR {
            get {
                return ResourceManager.GetString("TXT_CASO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay prestadores asignados.
        /// </summary>
        internal static string TXT_CASO_SIN_PRESTADOR {
            get {
                return ResourceManager.GetString("TXT_CASO_SIN_PRESTADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cargado el caso {0} correctamente en el sistema.
        /// </summary>
        internal static string TXT_CASO_SUCCESS {
            get {
                return ResourceManager.GetString("TXT_CASO_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija una opción.
        /// </summary>
        internal static string TXT_COMBO_ELIJA_OPCION {
            get {
                return ResourceManager.GetString("TXT_COMBO_ELIJA_OPCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se puede modificar el objeto. Es posible que otro usuario lo esté modificando en este momento. Intente en otro momento..
        /// </summary>
        internal static string TXT_CONCURENCY_ERROR {
            get {
                return ResourceManager.GetString("TXT_CONCURENCY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterAssist Travel.
        /// </summary>
        internal static string TXT_DEFAULT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("TXT_DEFAULT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe elegir una hubicacion válida.
        /// </summary>
        internal static string TXT_ERROR_UBICACION_EMPTY {
            get {
                return ResourceManager.GetString("TXT_ERROR_UBICACION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO Activo.
        /// </summary>
        internal static string TXT_NO_ACTIVO {
            get {
                return ResourceManager.GetString("TXT_NO_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay registros para mostrar.
        /// </summary>
        internal static string TXT_NON_RESULTS {
            get {
                return ResourceManager.GetString("TXT_NON_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Observaciones.
        /// </summary>
        internal static string TXT_OBSERVACIONES_SIN_OBS {
            get {
                return ResourceManager.GetString("TXT_OBSERVACIONES_SIN_OBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No se puede modificar el objeto. Es posible que otro usuario lo esté modificando en este momento. Intente en otro momento..
        /// </summary>
        internal static string TXT_PRESTADOR_ERROR {
            get {
                return ResourceManager.GetString("TXT_PRESTADOR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha cargado el Prestador {0} correctamente en el sistema.
        /// </summary>
        internal static string TXT_PRESTADOR_SUCCESS {
            get {
                return ResourceManager.GetString("TXT_PRESTADOR_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Prestador.
        /// </summary>
        internal static string TXT_PRESTADORES_INFORMACION {
            get {
                return ResourceManager.GetString("TXT_PRESTADORES_INFORMACION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros.
        /// </summary>
        internal static string TXT_RECORD_COUNT {
            get {
                return ResourceManager.GetString("TXT_RECORD_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Personales.
        /// </summary>
        internal static string TXT_SECCION_PERSONAL {
            get {
                return ResourceManager.GetString("TXT_SECCION_PERSONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos de la Póliza.
        /// </summary>
        internal static string TXT_SECCION_POLIZA {
            get {
                return ResourceManager.GetString("TXT_SECCION_POLIZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Vehículo.
        /// </summary>
        internal static string TXT_SESSION_VEHICULO {
            get {
                return ResourceManager.GetString("TXT_SESSION_VEHICULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Direccion.
        /// </summary>
        internal static string TXT_SIN_DIRECCION {
            get {
                return ResourceManager.GetString("TXT_SIN_DIRECCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Afiliado se ha creado correctamente en el sistema. ¿Agregar otro usuario?.
        /// </summary>
        internal static string TXT_SUCC_AFILIADO_CREATE {
            get {
                return ResourceManager.GetString("TXT_SUCC_AFILIADO_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Afiliado se ha modificado correctamente en el sistema..
        /// </summary>
        internal static string TXT_SUCC_AFILIADO_MODIF {
            get {
                return ResourceManager.GetString("TXT_SUCC_AFILIADO_MODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave se ha cambiado correctamente. Debe iniciar sesión con la nuevas credenciales..
        /// </summary>
        internal static string TXT_SUCC_CAMBIO_CLAVE {
            get {
                return ResourceManager.GetString("TXT_SUCC_CAMBIO_CLAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se ha creado correctamente en el sistema. ¿Agregar otro usuario?.
        /// </summary>
        internal static string TXT_SUCC_OPERADOR_CREATE {
            get {
                return ResourceManager.GetString("TXT_SUCC_OPERADOR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario se ha modificado correctamente en el sistema..
        /// </summary>
        internal static string TXT_SUCC_OPERADOR_MODIF {
            get {
                return ResourceManager.GetString("TXT_SUCC_OPERADOR_MODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Prestador se ha creado correctamente en el sistema. ¿Agregar otro Prestador?.
        /// </summary>
        internal static string TXT_SUCC_PRESTADOR_CREATE {
            get {
                return ResourceManager.GetString("TXT_SUCC_PRESTADOR_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Prestador se ha modificado correctamente en el sistema..
        /// </summary>
        internal static string TXT_SUCC_PRESTADOR_MODIF {
            get {
                return ResourceManager.GetString("TXT_SUCC_PRESTADOR_MODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El afiliado NO está activo..
        /// </summary>
        internal static string TXT_TOOL_TIP_AFILIADO_NO_ACTIVO {
            get {
                return ResourceManager.GetString("TXT_TOOL_TIP_AFILIADO_NO_ACTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/D.
        /// </summary>
        internal static string TXT_VALOR_NO_DISPONIBLE {
            get {
                return ResourceManager.GetString("TXT_VALOR_NO_DISPONIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Registros Huerfanos.
        /// </summary>
        internal static string TXT_VER_HUERFANOS {
            get {
                return ResourceManager.GetString("TXT_VER_HUERFANOS", resourceCulture);
            }
        }
    }
}
